apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: staging
spec:
  ports:
    - port: 4000
      protocol: TCP
  selector:
    app: server
#  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: backend-ingress
  namespace: staging
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: stag.backend.rafifauz.site
    http:
      paths:
      #- path: /belajar
      - backend:
          serviceName: backend-service
          servicePort: 4000
