apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: staging
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: raxer/backend-sp4
          ports:
            - containerPort: 4000
              name: nodejs-port
  selector:
    matchLabels:
      app: server
