apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: staging
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: http-port
  selector:
    app: client
#  type: LoadBalancer
---
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
 name: frontend-ssl
 namespace: staging
spec:
 acme:
   # The ACME server URL
   server: https://acme-v02.api.letsencrypt.org/directory
   # Email address used for ACME registration
   email: a@gmail.com
   # Name of a secret used to store the ACME account private key
   privateKeySecretRef:
     name: frontend-ssl
   # Enable the HTTP-01 challenge provider
   solvers:
   - selector: {}
     http01:
       ingress:
         class:  nginx
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: frontend-ingress
  namespace: staging
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/issuer: "frontend-ssl"
spec:
  rules:
  - host: stag.frontend.rafifauz.site
    http:
      paths:
      #- path: /belajar
      - backend:
          serviceName: frontend-service
          servicePort: 80

  tls:
  - hosts:
    - stag.frontend.rafifauz.site
    secretName: frontend-tls
